import { AiFillStar } from "react-icons/ai";

const products = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 10,
    discountPrice: 5,
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 50,
    discountPrice: 24,
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "Adidas Men's Pace VS-M",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 10,
    discountPrice: 5,
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 50,
    discountPrice: 24,
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "Adidas Men's Pace VS-M",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 10,
    discountPrice: 5,
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 50,
    discountPrice: 24,
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "Adidas Men's Pace VS-M",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 10,
    discountPrice: 5,
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 50,
    discountPrice: 24,
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "Adidas Men's Pace VS-M",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 10,
    discountPrice: 5,
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 50,
    discountPrice: 24,
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "Adidas Men's Pace VS-M",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 10,
    discountPrice: 5,
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 50,
    discountPrice: 24,
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "Adidas Men's Pace VS-M",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 10,
    discountPrice: 5,
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 50,
    discountPrice: 24,
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "Adidas Men's Pace VS-M",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 10,
    discountPrice: 5,
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 50,
    discountPrice: 24,
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "Adidas Men's Pace VS-M",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 10,
    discountPrice: 5,
    company: "Nike",
    color: "white",
    category: "sneakers",
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 50,
    discountPrice: 24,
    company: "Nike",
    color: "red",
    category: "sneakers"
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "Adidas Men's Pace VS-M",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "adidas Unisex-Adult Adilette Sandals",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "adidas Unisex-Adult Adilette Sandals",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "adidas Unisex-Adult Adilette Sandals",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "adidas Unisex-Adult Adilette Sandals",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "adidas Unisex-Adult Adilette Sandals",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "adidas Unisex-Adult Adilette Sandals",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "adidas Unisex-Adult Adilette Sandals",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "adidas Unisex-Adult Adilette Sandals",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "sandals",
  },
  {
    img: "https://m.media-amazon.com/images/I/71205al61QL._AC_UL400_.jpg",
    title: "adidas Unisex-Adult Adilette Sandals",
    star: <AiFillStar className="ratings-start" />,
    reviews: "(123 reviews)",
    price: 140,
    discountPrice: null,
    company: "Adidas",
    color: "black",
    category: "sandals",
  },
];

export default products;
